blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
  # exemplo: /
  url(r'^$', views.index, name='index'),
  # exemplo: /artigo/15
  url(r'^artigo/(?P<id_artigo>[0-9]+)/$', views.ver_artigo, name='ver_artigo'),
  # exemplo: /categoria/1
  url(r'^categoria/(?P<id_categoria>[0-9]+)/$', views.ver_artigos_categoria,
      name='ver_categoria'),
]

colombojrj/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
  url(r'^blog/',     include('blog.urls', namespace="blog")),
  url(r'^enquete/',  include('enquete.urls', namespace="enquete")),
  url(r'^ckeditor/', include('ckeditor_uploader.urls')),
  url(r'^admin/',    include(admin.site.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

enquete/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from . import views

urlpatterns = [
  # ex: /enquete
  url(r'^$', views.index, name='index'),
  # ex: /enquete/5
  url(r'^(?P<id_enquete>[0-9]+)/$', views.detalhes, name='detalhes'),
  # ex: /enquete/5/votar
  url(r'^(?P<id_enquete>[0-9]+)/votar/$', views.votar, name='votar'),
  # ex: /enquete/5/resultado
  url(r'^(?P<id_enquete>[0-9]+)/resultado/$',views.resultado,name='resultado'),
]

enquete/models.py
# -*- coding: utf-8 -*-

from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField

class Enquete(models.Model):
    titulo          = models.CharField(max_length=100, default='')
    preambulo       = RichTextUploadingField()
    slug            = models.SlugField(max_length=100, default='')
    data_publicacao = models.DateField('Data')
    
    def __str__(self):
        return self.titulo

class Pergunta(models.Model):
    formulario      = models.ForeignKey(Enquete)
    texto_pergunta  = RichTextUploadingField()
    slug            = models.SlugField(max_length=100)
    
    def __str__(self):
      return self.slug

class Escolha(models.Model):
    pergunta = models.ForeignKey(Pergunta)
    texto_escolha = models.CharField(max_length=200)
    votos = models.IntegerField(default=0)
    
    def __unicode__(self):
        return u'%s'%(self.texto_escolha)
    

    
    

enquete/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.forms import ModelForm
from .models import Enquete, Pergunta, Escolha

class FormularioEnquete(ModelForm):
    class Meta:
        model = Enquete
        fields = []
    
    def __init__(self, *args, **kwargs):
        enquete = kwargs.pop('enquete', '')
        super(FormularioEnquete, self).__init__(*args, **kwargs)
        for pergunta in enquete.pergunta_set.all():
            escolhas = pergunta.escolha_set.all()
            item = pergunta.texto_pergunta
            self.fields[item] = forms.ModelChoiceField(widget=forms.RadioSelect(attrs={'id': 'value'}), 
                                                       queryset=escolhas, 
                                                       empty_label=None,)
            self.fields[item].label = pergunta.texto_pergunta
    
    def save(self, enquete):
        for item in self.data:
            if item != 'csrfmiddlewaretoken':
                escolha_votada = Escolha.objects.get(pk=self.data[item])
                escolha_votada.votos = escolha_votada.votos + 1
                escolha_votada.save()
                

enquete/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from .models import Enquete, Pergunta, Escolha
from .forms import FormularioEnquete

def index(request):
    enquetes = Enquete.objects.order_by('-data_publicacao')[:5]

    context = {'enquetes': enquetes}
    
    return render(request, 'enquete/index.html', context)

def detalhes(request, id_enquete):
    # Pega a enquete que o internauta solicitou
    enquete = get_object_or_404(Enquete, pk=id_enquete)
    
    formulario = FormularioEnquete(enquete=enquete)
    
    context = {'enquete': enquete, 'formulario' : formulario}
    
    return render(request, 'enquete/detalhes.html', context)

def votar(request, id_enquete):
    enquete = get_object_or_404(Enquete, pk=id_enquete)
    
    formulario = FormularioEnquete(request.POST, enquete=enquete)
    
    if formulario.is_valid():
        formulario.save(enquete)
    
    
    #selected_choice = p.escolha_set.get(pk=request.POST['escolha'])
    #selected_choice.votos += 1
    #selected_choice.save()
    # Always return an HttpResponseRedirect after successfully dealing
    # with POST data. This prevents data from being posted twice if a
    # user hits the Back button.
    #return HttpResponseRedirect(reverse('enquete:resultado', args=(p.id,)))
    return HttpResponse('Obrigado pela sua participação!')

        
def resultado(request, id_enquete):
    enquete = get_object_or_404(Enquete, pk=id_enquete)
    return render(request, 'enquete/resultado.html', {'enquete': enquete})

enquete/templates/enquete/detalhes.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'enquete/enquete.css' %}" />

<h1> {% autoescape off %} {{ enquete.titulo }} {% endautoescape %} </h1>

<h3> {% autoescape off %} {{ enquete.preambulo }} {% endautoescape %} </h3>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'enquete:votar' enquete.id %}" method="post">
    {% csrf_token %}
    {% for pergunta in formulario %}
        <hr>
        {% autoescape off %} {{ pergunta.label }} {% endautoescape %}
        {{ pergunta }}
    {% endfor %}
    
    <input type="submit" value="Vai trem!" />
</form>

enquete/templates/enquete/index.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'enquete/enquete.css' %}" />

{% if enquetes %}
    <ul>
    {% for enquete in enquetes %}
        <li><a href={% url 'enquete:detalhes' enquete.id %}>{{ enquete.titulo }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>Nehuma enquete disponível.</p>
{% endif %}

enquete/templates/enquete/resultado.html
<h1>{{ pergunta.texto_pergunta }}</h1>

<ul>
{% for pergunta in enquete.pergunta_set.all %}
    {% autoescape off %} {{ pergunta.texto_pergunta }} {% endautoescape %}
    {% for escolha in pergunta.escolha_set.all%}
        <li>{% autoescape off %} {{ escolha.texto_escolha }} {% endautoescape %} -- {{ escolha.votos }} voto{{ escolha.votos|pluralize }}</li>
    {% endfor %}
{% endfor %}
</ul>