blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
  # exemplo: /
  url(r'^$', views.index, name='index'),
  # exemplo: /artigo/15
  url(r'^artigo/(?P<id_artigo>[0-9]+)/$', views.ver_artigo, name='ver_artigo'),
  # exemplo: /categoria/1
  url(r'^categoria/(?P<id_categoria>[0-9]+)/$', views.ver_artigos_categoria,
      name='ver_categoria'),
]

colombojrj/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
  url(r'^blog/',     include('blog.urls', namespace="blog")),
  url(r'^enquete/',  include('enquete.urls', namespace="enquete")),
  url(r'^ckeditor/', include('ckeditor_uploader.urls')),
  url(r'^admin/',    include(admin.site.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
# -*- coding: utf-8 -*-

from django.db import models
#from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

class Categoria(models.Model):
  titulo = models.CharField(max_length = 100)
  slug   = models.SlugField(max_length = 100)
            
  def __unicode__(self):
    return u'%s'%(self.titulo)

class Artigo(models.Model):
  titulo          = models.CharField(max_length = 100)
  #conteudo        = RichTextField()
  conteudo        = RichTextUploadingField()
  publicado       = models.BooleanField(default = False)
  data_publicacao = models.DateTimeField('Data', auto_now_add = True)
  autor           = models.CharField(max_length = 100)
  slug            = models.SlugField(max_length = 100, unique = True)
  categoria       = models.ForeignKey(Categoria)

  def __unicode__(self):
    return self.titulo

class Comentario(models.Model):
  conteudo        = models.CharField(max_length = 1000)
  artigo          = models.ForeignKey(Artigo)
  data_publicacao = models.DateTimeField('Data', auto_now_add = True)
  autor           = models.CharField(max_length = 100)
  publicado       = models.BooleanField(default = False)
  
  def __unicode__(self):
    return u'%s'%(self.conteudo)

blog/forms.py
# -*- coding: utf-8 -*-

from django import forms

class FormularioComentario(forms.Form):
    autor = forms.CharField(label='Nome', max_length=100)
    conteudo = forms.CharField(label=u'Comentário', 
                               max_length=1000, 
                               widget=forms.Textarea())
    

blog/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from .models import Artigo, Categoria, Comentario
from .forms import FormularioComentario

def index(request):
  # Carrega os últimos 5 artigos
  artigos = Artigo.objects.order_by('-data_publicacao')[:5]
  
  # Carrega todas as categorias
  categorias = Categoria.objects.all()
  
  # Organiza esses dados em um dicionários e os envia para visualização
  context = {"artigos"    : artigos,
             "categorias" : categorias}
  return render(request, 'blog/artigos.html', context)

def ver_artigo(request, id_artigo):
  # Carrega todas as categorias
  categorias = Categoria.objects.all()  
  context = {"categorias" : categorias}

  # Carrega o artigo selecionado
  artigo_selecionado = get_object_or_404(Artigo, pk=id_artigo)
  context["artigo"] = artigo_selecionado

  # Por enquanto, assume-se que nenhum formulário foi recebido
  context["comentario_recebido"] = False
  
  # "Pega" o formulário preenchido enviado pelo leitor
  if request.method == 'POST':
    formulario = FormularioComentario(request.POST)
    
    # Se o formulário é válido, então "pega" os campos preenchidos
    if formulario.is_valid():
      handle = Comentario(conteudo  = formulario.cleaned_data['conteudo'], 
                          autor     = formulario.cleaned_data['autor'],
                          artigo    = artigo_selecionado,
                          publicado = False)
      handle.save()
      context["comentario_recebido"] = True
    else:
      context["formulario"] = formulario
      
  else:
    # Carrega os comentários de um determinado artigo
    comentarios = artigo_selecionado.comentario_set.all()
    
    # Cria um formulário em branco para o leitor inserir um comentário
    formulario = FormularioComentario()
    
    # Organiza esses dados num dicionário
    context["comentarios"] = comentarios.order_by('-data_publicacao')[:5]
    context["formulario"]  = formulario
  
  return render(request, 'blog/artigo.html', context)

def ver_artigos_categoria(request, id_categoria):
  # Carrega a categoria escolhida pelo usuário
  categoria = Categoria.objects.get(pk=id_categoria)
  
  # Carrega todos os artigos dessa categoria
  artigos = categoria.artigo_set.order_by('-data_publicacao')
  
  # Carrega todas as categorias
  categorias = Categoria.objects.all()
  
  # Organiza esses dados num dicionário
  context = {"artigos"    : artigos,
             "categorias" : categorias}
             
  return render(request, 'blog/artigos.html', context)

blog/templates/blog/artigo.html
{% extends "blog/index.html" %}

{% block MainPage %}
    {% if artigo.publicado == True %}
        <article>
          <h3> <a href="{% url 'blog:ver_artigo' artigo.id %}"> {{ artigo.titulo }} </a> </h3>
          <h6> {{ artigo.data_publicacao }} </h6>

          {% block content %}
            {% autoescape off %} {{ artigo.conteudo }} {% endautoescape %}
          {% endblock %}
        </article>
        
        <!-- Barra horizontal -->
        <hr>
        
        <h3>Seção de comentários</h3>
        {% if comentarios %}
          {% for comentario in comentarios %}
            {% if comentario.publicado %}
              <h6> Por {{comentario.autor}}, em {{ comentario.data_publicacao }} </h6>
              {% block secao_comentarios %}
                {% autoescape off %} {{ comentario.conteudo }} {% endautoescape %}
              {% endblock %}
            {% endif %}
          {% endfor %}
        {% endif %}
        
        <hr>
        {% if comentario_recebido %}
          <h3>Comentário enviado com sucesso!</h3>
          <p>Seu comentário foi recebido e está aguardando moderação. Em breve será publicado!</p>
        {% else %}
          <h3>Novo comentário</h3>
          <form action="." method="post">
            {% load widget_tweaks %}
            {% csrf_token %}
            <p> 
              {{ formulario.autor.errors }}
              {{ formulario.autor.label }} <br> {{ formulario.autor|add_class:"comentario_autor" }} 
            </p>
            <p>
              {{ formulario.conteudo.errors }}
              {{ formulario.conteudo.label }} <br> {{ formulario.conteudo|add_class:"comentario_conteudo" }}
            </p>
            <input type="submit" value="Vai!" />
          </form>
        {% endif %}
    {% endif %}
{% endblock %}

blog/templates/blog/artigos.html
{% extends "blog/index.html" %}

{% block MainPage %}
    {% if artigos %}
        {% for artigo in artigos %}
            {% if artigo.publicado == True %}
                <article>
                  <h3> <a href="{% url 'blog:ver_artigo' artigo.id %}"> {{ artigo.titulo }} </a> </h3>
                  <h6> {{ artigo.data_publicacao }} </h6>

                  {% block content %}
                    {% autoescape off %} {{ artigo.conteudo }} {% endautoescape %}
                  {% endblock %}
                </article>
                
                <!-- Barra horizontal -->
                <hr />
            {% endif %}
        {% endfor %}
    {% else %}
        <p> Não existem artigos ainda! </p>
    {% endif %}
{% endblock %}

blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="pt"><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
    {% load staticfiles %}
    
    <link rel="stylesheet" href="{% static 'home/css/stylesheet.css' %}" />

    <title>José Roberto Colombo Junior</title>

  <body>

    <!-- HEADER -->
    <div id="header_wrap" class="outer">
        <header class="inner">

          <h1 id="project_title">José Roberto Colombo Junior</h1>
          <h2 id="project_tagline">Bem vindo ao meu blog</h2>

        </header>
    </div>
    
    <!-- MAIN CONTENT -->
    <div id="main_content_wrap" class="outer">
      <!-- Left Menu Bar -->
      <div id="nav" class="nav">
          <ul>
            <li id="home" class="active"><a href="/blog"> Categorias</a></li>
            {% for categoria in categorias %}
              <li><a href="{% url 'blog:ver_categoria' categoria.id %}">{{categoria.titulo}}</a></li>
            {% endfor %}
          </ul>
      </div>
      <section id="main_content" class="inner">

      {% block MainPage %} {% endblock %}
      <br>
  

</section>
    </div>

    <!-- FOOTER  -->
    <div id="footer_wrap" class="footer">
      <p> <a href="https://www.djangoproject.com/"> <img class="imagem_footer" src="{% static "home/img/django-powered.png" %}" alt="Feito com Django."></a> </p>
    </div>
  
</body></html>